CREATE TABLE movies
(
    id BIGSERIAL PRIMARY KEY,

    title VARCHAR(255) NOT NULL,

    language VARCHAR(100) NOT NULL,

    duration INTEGER NOT NULL,

    genre VARCHAR(100) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);