ALTER TABLE users
ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN role VARCHAR(30) NOT NULL DEFAULT 'CUSTOMER';

ALTER TABLE users
ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;